### PR TITLE
[#438] FIX import-ldif --offline "import has been aborted because the entry does not have a parent entry"

### LINKED ISSUE #438: The import has been aborted because the entry does not have a parent entry
**Describe the bug**

Re-emergence of #431 

On a fresh backend, I am once again seeing

```
[17/Oct/2024:20:06:00 -0700] category=BACKEND severity=ERROR msgID=-1 msg=failed to execute task exception=ExecutionException: org.opends.server.types.DirectoryException: The import has been aborted because the entry 'n=0,ou=Registrations,o=rA' does not have a parent entry (FutureTask.java:122 FutureTask.java:191 OnDiskMergeImporter.java:2798 OnDiskMergeImporter.java:1281 OnDiskMergeImporter.java:1040 OnDiskMergeImporter.java:154 OnDiskMergeImporter.java:228 BackendImpl.java:660 ImportLDIF.java:858 TaskTool.java:251 ImportLDIF.java:243 ImportLDIF.java:113 ImportLDIF.java:88)
[17/Oct/2024:20:06:00 -0700] category=BACKEND severity=NOTICE msgID=522 msg=Index /o=ra/entryUUID.uuidMatch phase two processing completed
[17/Oct/2024:20:06:00 -0700] category=BACKEND severity=NOTICE msgID=526 msg=Import LDIF environment close took 0 seconds
[17/Oct/2024:20:06:00 -0700] category=BACKEND severity=NOTICE msgID=518 msg=Flushing data to disk
[17/Oct/2024:20:06:00 -0700] category=BACKEND severity=ERROR msgID=481 msg=The import has been aborted because the entry 'n=0,ou=Registrations,o=rA' does not have a parent entry
```

Commands run:

```
$ sudo /opt/opendj/bin/dsconfig create-backend \
  -D "cn=Registration Authority" \
  -w secret \
  --backend-name=rA \
  -t je \
  --set=base-dn:o=rA \
  --set=enabled:true \
  --set=index-entry-limit:200000 \
  --no-prompt --trustAll

$ sudo /opt/opendj/bin/stop-ds

$ sudo /opt/opendj/bin/import-ldif \
  -D "cn=Registration Authority" \
  -w secret \
  --clearBackend \
  --backendID=rA \
  --ldifFile ~/dev/tmp/content.ldif \
  --offline
```
Note, I also tried without `--clearBackend` with the same result.

### PR DESCRIPTION
**Pull request by vharseko**
Closes #438

### CODE REVIEW

File: opendj-server-legacy/src/main/java/org/opends/server/backends/pluggable/DnKeyFormat.java [hunk 1]
```diff
@@ -132,6 +133,9 @@ static boolean isChild(ByteSequence parent, ByteSequence child)
       {
         if (childSeparatorDetected)
         {
+          if (child.byteAt(i-1)==NORMALIZED_ESC_BYTE) {
+            continue;
+          }
```
Comment (vharseko) [inline opendj-server-legacy/src/main/java/org/opends/server/backends/pluggable/DnKeyFormat.java:138]: problem cause

**Review by maximthomas — APPROVED** [review]
